/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/chris/Documents/mines/mines_grad/csci598/hcr_term_project/rocon/src/rocon_msgs/rocon_interaction_msgs/srv/GetInteraction.srv
 *
 */


#ifndef ROCON_INTERACTION_MSGS_MESSAGE_GETINTERACTION_H
#define ROCON_INTERACTION_MSGS_MESSAGE_GETINTERACTION_H

#include <ros/service_traits.h>


#include <rocon_interaction_msgs/GetInteractionRequest.h>
#include <rocon_interaction_msgs/GetInteractionResponse.h>


namespace rocon_interaction_msgs
{

struct GetInteraction
{

typedef GetInteractionRequest Request;
typedef GetInteractionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInteraction
} // namespace rocon_interaction_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rocon_interaction_msgs::GetInteraction > {
  static const char* value()
  {
    return "30e8310e8aa2396e785d9cc40638555f";
  }

  static const char* value(const ::rocon_interaction_msgs::GetInteraction&) { return value(); }
};

template<>
struct DataType< ::rocon_interaction_msgs::GetInteraction > {
  static const char* value()
  {
    return "rocon_interaction_msgs/GetInteraction";
  }

  static const char* value(const ::rocon_interaction_msgs::GetInteraction&) { return value(); }
};


// service_traits::MD5Sum< ::rocon_interaction_msgs::GetInteractionRequest> should match 
// service_traits::MD5Sum< ::rocon_interaction_msgs::GetInteraction > 
template<>
struct MD5Sum< ::rocon_interaction_msgs::GetInteractionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_interaction_msgs::GetInteraction >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetInteractionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_interaction_msgs::GetInteractionRequest> should match 
// service_traits::DataType< ::rocon_interaction_msgs::GetInteraction > 
template<>
struct DataType< ::rocon_interaction_msgs::GetInteractionRequest>
{
  static const char* value()
  {
    return DataType< ::rocon_interaction_msgs::GetInteraction >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetInteractionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rocon_interaction_msgs::GetInteractionResponse> should match 
// service_traits::MD5Sum< ::rocon_interaction_msgs::GetInteraction > 
template<>
struct MD5Sum< ::rocon_interaction_msgs::GetInteractionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_interaction_msgs::GetInteraction >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetInteractionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_interaction_msgs::GetInteractionResponse> should match 
// service_traits::DataType< ::rocon_interaction_msgs::GetInteraction > 
template<>
struct DataType< ::rocon_interaction_msgs::GetInteractionResponse>
{
  static const char* value()
  {
    return DataType< ::rocon_interaction_msgs::GetInteraction >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetInteractionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROCON_INTERACTION_MSGS_MESSAGE_GETINTERACTION_H
