/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/chris/Documents/mines/mines_grad/csci598/hcr_term_project/rocon/src/rocon_msgs/rocon_interaction_msgs/srv/GetRoles.srv
 *
 */


#ifndef ROCON_INTERACTION_MSGS_MESSAGE_GETROLES_H
#define ROCON_INTERACTION_MSGS_MESSAGE_GETROLES_H

#include <ros/service_traits.h>


#include <rocon_interaction_msgs/GetRolesRequest.h>
#include <rocon_interaction_msgs/GetRolesResponse.h>


namespace rocon_interaction_msgs
{

struct GetRoles
{

typedef GetRolesRequest Request;
typedef GetRolesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRoles
} // namespace rocon_interaction_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rocon_interaction_msgs::GetRoles > {
  static const char* value()
  {
    return "bb1af0e7038bd0c25a66561b0d17c47c";
  }

  static const char* value(const ::rocon_interaction_msgs::GetRoles&) { return value(); }
};

template<>
struct DataType< ::rocon_interaction_msgs::GetRoles > {
  static const char* value()
  {
    return "rocon_interaction_msgs/GetRoles";
  }

  static const char* value(const ::rocon_interaction_msgs::GetRoles&) { return value(); }
};


// service_traits::MD5Sum< ::rocon_interaction_msgs::GetRolesRequest> should match 
// service_traits::MD5Sum< ::rocon_interaction_msgs::GetRoles > 
template<>
struct MD5Sum< ::rocon_interaction_msgs::GetRolesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_interaction_msgs::GetRoles >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetRolesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_interaction_msgs::GetRolesRequest> should match 
// service_traits::DataType< ::rocon_interaction_msgs::GetRoles > 
template<>
struct DataType< ::rocon_interaction_msgs::GetRolesRequest>
{
  static const char* value()
  {
    return DataType< ::rocon_interaction_msgs::GetRoles >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetRolesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rocon_interaction_msgs::GetRolesResponse> should match 
// service_traits::MD5Sum< ::rocon_interaction_msgs::GetRoles > 
template<>
struct MD5Sum< ::rocon_interaction_msgs::GetRolesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_interaction_msgs::GetRoles >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetRolesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_interaction_msgs::GetRolesResponse> should match 
// service_traits::DataType< ::rocon_interaction_msgs::GetRoles > 
template<>
struct DataType< ::rocon_interaction_msgs::GetRolesResponse>
{
  static const char* value()
  {
    return DataType< ::rocon_interaction_msgs::GetRoles >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetRolesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROCON_INTERACTION_MSGS_MESSAGE_GETROLES_H
