/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/marshall/hcr_term_project/turtlebot/src/map_store/srv/RenameMap.srv
 *
 */


#ifndef MAP_STORE_MESSAGE_RENAMEMAP_H
#define MAP_STORE_MESSAGE_RENAMEMAP_H

#include <ros/service_traits.h>


#include <map_store/RenameMapRequest.h>
#include <map_store/RenameMapResponse.h>


namespace map_store
{

struct RenameMap
{

typedef RenameMapRequest Request;
typedef RenameMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RenameMap
} // namespace map_store


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_store::RenameMap > {
  static const char* value()
  {
    return "94f4d84fa2d3173899807933af417784";
  }

  static const char* value(const ::map_store::RenameMap&) { return value(); }
};

template<>
struct DataType< ::map_store::RenameMap > {
  static const char* value()
  {
    return "map_store/RenameMap";
  }

  static const char* value(const ::map_store::RenameMap&) { return value(); }
};


// service_traits::MD5Sum< ::map_store::RenameMapRequest> should match 
// service_traits::MD5Sum< ::map_store::RenameMap > 
template<>
struct MD5Sum< ::map_store::RenameMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_store::RenameMap >::value();
  }
  static const char* value(const ::map_store::RenameMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_store::RenameMapRequest> should match 
// service_traits::DataType< ::map_store::RenameMap > 
template<>
struct DataType< ::map_store::RenameMapRequest>
{
  static const char* value()
  {
    return DataType< ::map_store::RenameMap >::value();
  }
  static const char* value(const ::map_store::RenameMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_store::RenameMapResponse> should match 
// service_traits::MD5Sum< ::map_store::RenameMap > 
template<>
struct MD5Sum< ::map_store::RenameMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_store::RenameMap >::value();
  }
  static const char* value(const ::map_store::RenameMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_store::RenameMapResponse> should match 
// service_traits::DataType< ::map_store::RenameMap > 
template<>
struct DataType< ::map_store::RenameMapResponse>
{
  static const char* value()
  {
    return DataType< ::map_store::RenameMap >::value();
  }
  static const char* value(const ::map_store::RenameMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_STORE_MESSAGE_RENAMEMAP_H
