/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/marshall/hcr_term_project/turtlebot/devel/share/pano_ros/msg/PanoCaptureResult.msg
 *
 */


#ifndef PANO_ROS_MESSAGE_PANOCAPTURERESULT_H
#define PANO_ROS_MESSAGE_PANOCAPTURERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pano_ros
{
template <class ContainerAllocator>
struct PanoCaptureResult_
{
  typedef PanoCaptureResult_<ContainerAllocator> Type;

  PanoCaptureResult_()
    : pano_id(0)
    , n_captures(0)
    , bag_filename()  {
    }
  PanoCaptureResult_(const ContainerAllocator& _alloc)
    : pano_id(0)
    , n_captures(0)
    , bag_filename(_alloc)  {
    }



   typedef uint32_t _pano_id_type;
  _pano_id_type pano_id;

   typedef uint32_t _n_captures_type;
  _n_captures_type n_captures;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _bag_filename_type;
  _bag_filename_type bag_filename;




  typedef boost::shared_ptr< ::pano_ros::PanoCaptureResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pano_ros::PanoCaptureResult_<ContainerAllocator> const> ConstPtr;

}; // struct PanoCaptureResult_

typedef ::pano_ros::PanoCaptureResult_<std::allocator<void> > PanoCaptureResult;

typedef boost::shared_ptr< ::pano_ros::PanoCaptureResult > PanoCaptureResultPtr;
typedef boost::shared_ptr< ::pano_ros::PanoCaptureResult const> PanoCaptureResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pano_ros::PanoCaptureResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pano_ros::PanoCaptureResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pano_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'pano_ros': ['/home/marshall/hcr_term_project/turtlebot/devel/share/pano_ros/msg', '/home/marshall/hcr_term_project/turtlebot/src/turtlebot_apps/software/pano/pano_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pano_ros::PanoCaptureResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pano_ros::PanoCaptureResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pano_ros::PanoCaptureResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pano_ros::PanoCaptureResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pano_ros::PanoCaptureResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pano_ros::PanoCaptureResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pano_ros::PanoCaptureResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d1ff824dbed21bb16f220c4d06a45fb";
  }

  static const char* value(const ::pano_ros::PanoCaptureResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d1ff824dbed21bbULL;
  static const uint64_t static_value2 = 0x16f220c4d06a45fbULL;
};

template<class ContainerAllocator>
struct DataType< ::pano_ros::PanoCaptureResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pano_ros/PanoCaptureResult";
  }

  static const char* value(const ::pano_ros::PanoCaptureResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pano_ros::PanoCaptureResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
uint32 pano_id\n\
uint32 n_captures\n\
string bag_filename\n\
";
  }

  static const char* value(const ::pano_ros::PanoCaptureResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pano_ros::PanoCaptureResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pano_id);
      stream.next(m.n_captures);
      stream.next(m.bag_filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PanoCaptureResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pano_ros::PanoCaptureResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pano_ros::PanoCaptureResult_<ContainerAllocator>& v)
  {
    s << indent << "pano_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pano_id);
    s << indent << "n_captures: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.n_captures);
    s << indent << "bag_filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.bag_filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANO_ROS_MESSAGE_PANOCAPTURERESULT_H
