; Auto-generated. Do not edit!


(cl:in-package pano_ros-msg)


;//! \htmlinclude PanoCaptureGoal.msg.html

(cl:defclass <PanoCaptureGoal> (roslisp-msg-protocol:ros-message)
  ((camera_topic
    :reader camera_topic
    :initarg :camera_topic
    :type cl:string
    :initform "")
   (bag_filename
    :reader bag_filename
    :initarg :bag_filename
    :type cl:string
    :initform ""))
)

(cl:defclass PanoCaptureGoal (<PanoCaptureGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PanoCaptureGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PanoCaptureGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pano_ros-msg:<PanoCaptureGoal> is deprecated: use pano_ros-msg:PanoCaptureGoal instead.")))

(cl:ensure-generic-function 'camera_topic-val :lambda-list '(m))
(cl:defmethod camera_topic-val ((m <PanoCaptureGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pano_ros-msg:camera_topic-val is deprecated.  Use pano_ros-msg:camera_topic instead.")
  (camera_topic m))

(cl:ensure-generic-function 'bag_filename-val :lambda-list '(m))
(cl:defmethod bag_filename-val ((m <PanoCaptureGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pano_ros-msg:bag_filename-val is deprecated.  Use pano_ros-msg:bag_filename instead.")
  (bag_filename m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PanoCaptureGoal>) ostream)
  "Serializes a message object of type '<PanoCaptureGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'camera_topic))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'camera_topic))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'bag_filename))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'bag_filename))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PanoCaptureGoal>) istream)
  "Deserializes a message object of type '<PanoCaptureGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'camera_topic) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'camera_topic) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'bag_filename) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'bag_filename) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PanoCaptureGoal>)))
  "Returns string type for a message object of type '<PanoCaptureGoal>"
  "pano_ros/PanoCaptureGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PanoCaptureGoal)))
  "Returns string type for a message object of type 'PanoCaptureGoal"
  "pano_ros/PanoCaptureGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PanoCaptureGoal>)))
  "Returns md5sum for a message object of type '<PanoCaptureGoal>"
  "d8d56113630df8b56f39dd99ce661288")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PanoCaptureGoal)))
  "Returns md5sum for a message object of type 'PanoCaptureGoal"
  "d8d56113630df8b56f39dd99ce661288")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PanoCaptureGoal>)))
  "Returns full string definition for message of type '<PanoCaptureGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%# TODO: tf frame ~%string camera_topic~%string bag_filename~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PanoCaptureGoal)))
  "Returns full string definition for message of type 'PanoCaptureGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%# TODO: tf frame ~%string camera_topic~%string bag_filename~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PanoCaptureGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'camera_topic))
     4 (cl:length (cl:slot-value msg 'bag_filename))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PanoCaptureGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PanoCaptureGoal
    (cl:cons ':camera_topic (camera_topic msg))
    (cl:cons ':bag_filename (bag_filename msg))
))
