; Auto-generated. Do not edit!


(cl:in-package pano_ros-msg)


;//! \htmlinclude PanoCaptureFeedback.msg.html

(cl:defclass <PanoCaptureFeedback> (roslisp-msg-protocol:ros-message)
  ((n_captures
    :reader n_captures
    :initarg :n_captures
    :type cl:float
    :initform 0.0))
)

(cl:defclass PanoCaptureFeedback (<PanoCaptureFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PanoCaptureFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PanoCaptureFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pano_ros-msg:<PanoCaptureFeedback> is deprecated: use pano_ros-msg:PanoCaptureFeedback instead.")))

(cl:ensure-generic-function 'n_captures-val :lambda-list '(m))
(cl:defmethod n_captures-val ((m <PanoCaptureFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pano_ros-msg:n_captures-val is deprecated.  Use pano_ros-msg:n_captures instead.")
  (n_captures m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PanoCaptureFeedback>) ostream)
  "Serializes a message object of type '<PanoCaptureFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'n_captures))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PanoCaptureFeedback>) istream)
  "Deserializes a message object of type '<PanoCaptureFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'n_captures) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PanoCaptureFeedback>)))
  "Returns string type for a message object of type '<PanoCaptureFeedback>"
  "pano_ros/PanoCaptureFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PanoCaptureFeedback)))
  "Returns string type for a message object of type 'PanoCaptureFeedback"
  "pano_ros/PanoCaptureFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PanoCaptureFeedback>)))
  "Returns md5sum for a message object of type '<PanoCaptureFeedback>"
  "22ff7abf8b5e4a280047b5a08afb8cf1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PanoCaptureFeedback)))
  "Returns md5sum for a message object of type 'PanoCaptureFeedback"
  "22ff7abf8b5e4a280047b5a08afb8cf1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PanoCaptureFeedback>)))
  "Returns full string definition for message of type '<PanoCaptureFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 n_captures~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PanoCaptureFeedback)))
  "Returns full string definition for message of type 'PanoCaptureFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 n_captures~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PanoCaptureFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PanoCaptureFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PanoCaptureFeedback
    (cl:cons ':n_captures (n_captures msg))
))
