; Auto-generated. Do not edit!


(cl:in-package pano_ros-msg)


;//! \htmlinclude StitchGoal.msg.html

(cl:defclass <StitchGoal> (roslisp-msg-protocol:ros-message)
  ((bag_file_name
    :reader bag_file_name
    :initarg :bag_file_name
    :type cl:string
    :initform "")
   (stitch_file_name
    :reader stitch_file_name
    :initarg :stitch_file_name
    :type cl:string
    :initform ""))
)

(cl:defclass StitchGoal (<StitchGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StitchGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StitchGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pano_ros-msg:<StitchGoal> is deprecated: use pano_ros-msg:StitchGoal instead.")))

(cl:ensure-generic-function 'bag_file_name-val :lambda-list '(m))
(cl:defmethod bag_file_name-val ((m <StitchGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pano_ros-msg:bag_file_name-val is deprecated.  Use pano_ros-msg:bag_file_name instead.")
  (bag_file_name m))

(cl:ensure-generic-function 'stitch_file_name-val :lambda-list '(m))
(cl:defmethod stitch_file_name-val ((m <StitchGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pano_ros-msg:stitch_file_name-val is deprecated.  Use pano_ros-msg:stitch_file_name instead.")
  (stitch_file_name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StitchGoal>) ostream)
  "Serializes a message object of type '<StitchGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'bag_file_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'bag_file_name))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'stitch_file_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'stitch_file_name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StitchGoal>) istream)
  "Deserializes a message object of type '<StitchGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'bag_file_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'bag_file_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'stitch_file_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'stitch_file_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StitchGoal>)))
  "Returns string type for a message object of type '<StitchGoal>"
  "pano_ros/StitchGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StitchGoal)))
  "Returns string type for a message object of type 'StitchGoal"
  "pano_ros/StitchGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StitchGoal>)))
  "Returns md5sum for a message object of type '<StitchGoal>"
  "2286405d213866ca1e7b46f37127c016")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StitchGoal)))
  "Returns md5sum for a message object of type 'StitchGoal"
  "2286405d213866ca1e7b46f37127c016")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StitchGoal>)))
  "Returns full string definition for message of type '<StitchGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%#full path to the input bag that has atleast camera_info and image messages~%string bag_file_name~%#full path to the desired output file. jpg or png extension required~%string stitch_file_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StitchGoal)))
  "Returns full string definition for message of type 'StitchGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%#full path to the input bag that has atleast camera_info and image messages~%string bag_file_name~%#full path to the desired output file. jpg or png extension required~%string stitch_file_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StitchGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'bag_file_name))
     4 (cl:length (cl:slot-value msg 'stitch_file_name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StitchGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StitchGoal
    (cl:cons ':bag_file_name (bag_file_name msg))
    (cl:cons ':stitch_file_name (stitch_file_name msg))
))
