(cl:defpackage gateway_msgs-msg
  (:use )
  (:export
   "<REMOTERULEWITHSTATUS>"
   "REMOTERULEWITHSTATUS"
   "<CONNECTIONSTATISTICS>"
   "CONNECTIONSTATISTICS"
   "<REMOTEGATEWAY>"
   "REMOTEGATEWAY"
   "<RULE>"
   "RULE"
   "<ERRORCODES>"
   "ERRORCODES"
   "<REMOTERULE>"
   "REMOTERULE"
   "<CONNECTIONTYPE>"
   "CONNECTIONTYPE"
   "<GATEWAYINFO>"
   "GATEWAYINFO"
  ))

