(cl:defpackage rocon_std_msgs-msg
  (:use )
  (:export
   "<PLATFORMINFO>"
   "PLATFORMINFO"
   "<REMAPPING>"
   "REMAPPING"
   "<STRINGARRAY>"
   "STRINGARRAY"
   "<ICON>"
   "ICON"
   "<KEYVALUE>"
   "KEYVALUE"
   "<MASTERINFO>"
   "MASTERINFO"
   "<STRINGS>"
   "STRINGS"
   "<STRINGSPAIRRESPONSE>"
   "STRINGSPAIRRESPONSE"
   "<STRINGSREQUEST>"
   "STRINGSREQUEST"
   "<STRINGSRESPONSE>"
   "STRINGSRESPONSE"
   "<STRINGSPAIRREQUEST>"
   "STRINGSPAIRREQUEST"
   "<STRINGSPAIR>"
   "STRINGSPAIR"
  ))

