/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/chris/Documents/mines/mines_grad/csci598/hcr_term_project/rocon/src/rocon_msgs/rocon_std_msgs/srv/GetPlatformInfo.srv
 *
 */


#ifndef ROCON_STD_MSGS_MESSAGE_GETPLATFORMINFO_H
#define ROCON_STD_MSGS_MESSAGE_GETPLATFORMINFO_H

#include <ros/service_traits.h>


#include <rocon_std_msgs/GetPlatformInfoRequest.h>
#include <rocon_std_msgs/GetPlatformInfoResponse.h>


namespace rocon_std_msgs
{

struct GetPlatformInfo
{

typedef GetPlatformInfoRequest Request;
typedef GetPlatformInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPlatformInfo
} // namespace rocon_std_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rocon_std_msgs::GetPlatformInfo > {
  static const char* value()
  {
    return "b7b34c89d857c757ff89bd8e49fa695f";
  }

  static const char* value(const ::rocon_std_msgs::GetPlatformInfo&) { return value(); }
};

template<>
struct DataType< ::rocon_std_msgs::GetPlatformInfo > {
  static const char* value()
  {
    return "rocon_std_msgs/GetPlatformInfo";
  }

  static const char* value(const ::rocon_std_msgs::GetPlatformInfo&) { return value(); }
};


// service_traits::MD5Sum< ::rocon_std_msgs::GetPlatformInfoRequest> should match 
// service_traits::MD5Sum< ::rocon_std_msgs::GetPlatformInfo > 
template<>
struct MD5Sum< ::rocon_std_msgs::GetPlatformInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_std_msgs::GetPlatformInfo >::value();
  }
  static const char* value(const ::rocon_std_msgs::GetPlatformInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_std_msgs::GetPlatformInfoRequest> should match 
// service_traits::DataType< ::rocon_std_msgs::GetPlatformInfo > 
template<>
struct DataType< ::rocon_std_msgs::GetPlatformInfoRequest>
{
  static const char* value()
  {
    return DataType< ::rocon_std_msgs::GetPlatformInfo >::value();
  }
  static const char* value(const ::rocon_std_msgs::GetPlatformInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rocon_std_msgs::GetPlatformInfoResponse> should match 
// service_traits::MD5Sum< ::rocon_std_msgs::GetPlatformInfo > 
template<>
struct MD5Sum< ::rocon_std_msgs::GetPlatformInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_std_msgs::GetPlatformInfo >::value();
  }
  static const char* value(const ::rocon_std_msgs::GetPlatformInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_std_msgs::GetPlatformInfoResponse> should match 
// service_traits::DataType< ::rocon_std_msgs::GetPlatformInfo > 
template<>
struct DataType< ::rocon_std_msgs::GetPlatformInfoResponse>
{
  static const char* value()
  {
    return DataType< ::rocon_std_msgs::GetPlatformInfo >::value();
  }
  static const char* value(const ::rocon_std_msgs::GetPlatformInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROCON_STD_MSGS_MESSAGE_GETPLATFORMINFO_H
