/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/chris/Documents/mines/mines_grad/csci598/hcr_term_project/rocon/src/rocon_msgs/concert_msgs/srv/EnableService.srv
 *
 */


#ifndef CONCERT_MSGS_MESSAGE_ENABLESERVICE_H
#define CONCERT_MSGS_MESSAGE_ENABLESERVICE_H

#include <ros/service_traits.h>


#include <concert_msgs/EnableServiceRequest.h>
#include <concert_msgs/EnableServiceResponse.h>


namespace concert_msgs
{

struct EnableService
{

typedef EnableServiceRequest Request;
typedef EnableServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableService
} // namespace concert_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::concert_msgs::EnableService > {
  static const char* value()
  {
    return "1cec37e7e5df14d95c8bda48b6179b1a";
  }

  static const char* value(const ::concert_msgs::EnableService&) { return value(); }
};

template<>
struct DataType< ::concert_msgs::EnableService > {
  static const char* value()
  {
    return "concert_msgs/EnableService";
  }

  static const char* value(const ::concert_msgs::EnableService&) { return value(); }
};


// service_traits::MD5Sum< ::concert_msgs::EnableServiceRequest> should match 
// service_traits::MD5Sum< ::concert_msgs::EnableService > 
template<>
struct MD5Sum< ::concert_msgs::EnableServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::concert_msgs::EnableService >::value();
  }
  static const char* value(const ::concert_msgs::EnableServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::concert_msgs::EnableServiceRequest> should match 
// service_traits::DataType< ::concert_msgs::EnableService > 
template<>
struct DataType< ::concert_msgs::EnableServiceRequest>
{
  static const char* value()
  {
    return DataType< ::concert_msgs::EnableService >::value();
  }
  static const char* value(const ::concert_msgs::EnableServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::concert_msgs::EnableServiceResponse> should match 
// service_traits::MD5Sum< ::concert_msgs::EnableService > 
template<>
struct MD5Sum< ::concert_msgs::EnableServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::concert_msgs::EnableService >::value();
  }
  static const char* value(const ::concert_msgs::EnableServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::concert_msgs::EnableServiceResponse> should match 
// service_traits::DataType< ::concert_msgs::EnableService > 
template<>
struct DataType< ::concert_msgs::EnableServiceResponse>
{
  static const char* value()
  {
    return DataType< ::concert_msgs::EnableService >::value();
  }
  static const char* value(const ::concert_msgs::EnableServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONCERT_MSGS_MESSAGE_ENABLESERVICE_H
