/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/marshall/hcr_term_project/turtlebot/src/turtlebot_create/create_node/srv/SetTurtlebotMode.srv
 *
 */


#ifndef CREATE_NODE_MESSAGE_SETTURTLEBOTMODE_H
#define CREATE_NODE_MESSAGE_SETTURTLEBOTMODE_H

#include <ros/service_traits.h>


#include <create_node/SetTurtlebotModeRequest.h>
#include <create_node/SetTurtlebotModeResponse.h>


namespace create_node
{

struct SetTurtlebotMode
{

typedef SetTurtlebotModeRequest Request;
typedef SetTurtlebotModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTurtlebotMode
} // namespace create_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::create_node::SetTurtlebotMode > {
  static const char* value()
  {
    return "652c4fe00e931153f82f8af90f1da441";
  }

  static const char* value(const ::create_node::SetTurtlebotMode&) { return value(); }
};

template<>
struct DataType< ::create_node::SetTurtlebotMode > {
  static const char* value()
  {
    return "create_node/SetTurtlebotMode";
  }

  static const char* value(const ::create_node::SetTurtlebotMode&) { return value(); }
};


// service_traits::MD5Sum< ::create_node::SetTurtlebotModeRequest> should match 
// service_traits::MD5Sum< ::create_node::SetTurtlebotMode > 
template<>
struct MD5Sum< ::create_node::SetTurtlebotModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::create_node::SetTurtlebotMode >::value();
  }
  static const char* value(const ::create_node::SetTurtlebotModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::create_node::SetTurtlebotModeRequest> should match 
// service_traits::DataType< ::create_node::SetTurtlebotMode > 
template<>
struct DataType< ::create_node::SetTurtlebotModeRequest>
{
  static const char* value()
  {
    return DataType< ::create_node::SetTurtlebotMode >::value();
  }
  static const char* value(const ::create_node::SetTurtlebotModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::create_node::SetTurtlebotModeResponse> should match 
// service_traits::MD5Sum< ::create_node::SetTurtlebotMode > 
template<>
struct MD5Sum< ::create_node::SetTurtlebotModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::create_node::SetTurtlebotMode >::value();
  }
  static const char* value(const ::create_node::SetTurtlebotModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::create_node::SetTurtlebotModeResponse> should match 
// service_traits::DataType< ::create_node::SetTurtlebotMode > 
template<>
struct DataType< ::create_node::SetTurtlebotModeResponse>
{
  static const char* value()
  {
    return DataType< ::create_node::SetTurtlebotMode >::value();
  }
  static const char* value(const ::create_node::SetTurtlebotModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CREATE_NODE_MESSAGE_SETTURTLEBOTMODE_H
